site_name: My Docs
theme:
  name: material
plugins:
  search:
    lang: "ja"

nav:
  - top: index.md
  - PHP:
      - debug tool: PHP/debug.md
      - Laravel:
          - コマンド: PHP/Laravel/command_cheat_sheet.md
          - 参考リンク: PHP/Laravel/links.md
